import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { digest, type WorkView } from "./contracts.js";
import { readContainedSource, sameDirectory, RouterError, type RouterConfiguration } from "./routing.js";
import type { OperationStore } from "./state-store.js";

export const PROGRESS_START = "<!-- FAL-OBSERVED-PROGRESS:BEGIN -->";
export const PROGRESS_END = "<!-- FAL-OBSERVED-PROGRESS:END -->";

export function progressBounds(content: string) {
  const start = content.indexOf(PROGRESS_START), end = content.indexOf(PROGRESS_END);
  if (start < 0 || end < start || content.indexOf(PROGRESS_START, start + 1) >= 0 || content.indexOf(PROGRESS_END, end + 1) >= 0) throw new RouterError("PROJECTION_MARKERS_INVALID");
  return { start: start + PROGRESS_START.length, end };
}

/** Only enrolled generated bytes may change without invalidating human authority. */
export function stateAuthorityDigest(content: string) {
  const bounds = progressBounds(content);
  return digest(content.slice(0, bounds.start) + content.slice(bounds.end));
}

const cell = (value: string | null | undefined) => value && /^[A-Za-z0-9 _./:-]{1,100}$/.test(value) && !/(?:ses_|msg_|https?:)/.test(value) ? value : "see retained result";
export function renderProgress(works: WorkView[]): string {
  const rows = works.map(work => {
    const product = work.operations.filter(operation => ["LIFECYCLE", "LEGACY"].includes(operation.action.kind)).at(-1);
    const maintenance = work.operations.filter(operation => ["COMPACT", "RESTORE"].includes(operation.action.kind)).at(-1);
    const fact = (operation: typeof product) => operation ? `${cell(operation.action.command)}: ${operation.outcome?.execution ?? (operation.dispatchStartedAt ? "PENDING" : "PREPARED")}` : "NONE";
    const delivery = product ? (product.acknowledgedAt ? "DELIVERED" : product.dispatchStartedAt || product.action.kind === "LEGACY" ? "POSSIBLE" : "NOT_SENT") : "NONE";
    return `| ${cell(work.context.workId)} | ${product ? cell(product.action.recipientRole) : "NONE"} | ${fact(product)} / ${delivery} | ${product?.interpretation ? cell(product.interpretation.decision) : "NOT_RECORDED"} | ${work.paused ? "YES" : "NO"} | ${fact(maintenance)} | ${product ? cell(product.operationId) : "NONE"} |`;
  });
  return `## Observed workflow progress (generated, advisory)\n\nThis block reports operation facts, not permission, product acceptance or the next dispatch.\nOwner/Meta intent and stop conditions outside this block remain authoritative.\nLatest 12 registered works at most; older records remain available through FAL inspect.\n\n| Work | Lane | Latest product operation / delivery | Reported interpretation | Owner pause | Latest maintenance | Evidence operation |\n|---|---|---|---|---|---|---|\n${rows.join("\n")}\n\nUse inspect/read-result to check evidence before dependent work. No lifecycle replay from stale prose.\n`;
}

export interface ProjectionResult { status: string; reason?: string; recoveryFile?: string }
/** Personal-scope operator capability, separate from a lane's immutable effect envelope. */
export function refreshState(store: OperationStore, configuration: RouterConfiguration, workId: string): ProjectionResult {
  try {
    const current = store.getWork(workId), target = configuration.targets[current.context.target];
    const enrollment = target?.stateProjection;
    if (!enrollment) return { status: "NOT_ENROLLED" };
    if (!enrollment.instructionReference?.trim() || !sameDirectory(target.directory, current.context.directory) ||
      path.posix.basename(enrollment.path.replaceAll("\\", "/")) !== "PROJECT_STATE.md") throw new RouterError("PROJECTION_ENROLLMENT_INVALID");
    const state = readContainedSource(target.directory, enrollment.path);
    const bounds = progressBounds(state.content);
    const ids = [workId, ...store.listRecentWorkIds(current.context.target).filter(id => id !== workId)].slice(0, 12);
    const works = ids.map(id => store.getWork(id)).filter(work => sameDirectory(work.context.directory, target.directory));
    // Old prepared operations used whole-file fences; never invalidate those by refreshing a view.
    if (store.hasPendingFullStateSource(current.context.target, target.directory, state.path)) return { status: "DEFERRED", reason: "LEGACY_STATE_SOURCE_IN_FLIGHT" };
    const body = renderProgress(works);
    const priorBody = state.content.slice(bounds.start, bounds.end).trim().replace(/^Updated by FAL: [^\n]+\n\n/, "");
    if (priorBody === body.trim()) return { status: "UNCHANGED" };
    if (process.platform !== "win32") return { status: "DEFERRED", reason: "ATOMIC_STATE_WRITER_REQUIRES_WINDOWS" };
    const helper = fileURLToPath(new URL("../../../scripts/write-observed-progress.ps1", import.meta.url));
    const result = spawnSync("powershell.exe", ["-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-File", helper], {
      input: JSON.stringify({ root: target.directory, relativePath: state.path, expectedSha256: state.sha256, body: `Updated by FAL: ${new Date().toISOString()}\n\n${body}` }),
      encoding: "utf8", windowsHide: true, maxBuffer: 128 * 1024,
    });
    if (result.error || result.status !== 0) return { status: "DEFERRED", reason: "STATE_WRITER_UNAVAILABLE" };
    return JSON.parse(result.stdout.trim()) as ProjectionResult;
  } catch (error) { return { status: "DEFERRED", reason: error instanceof RouterError ? error.code : "STATE_PROJECTION_UNAVAILABLE" }; }
}
